@QuantityMeasurementApp.HistoryService_HostAddress = http://localhost:5295

GET {{QuantityMeasurementApp.HistoryService_HostAddress}}/health
Accept: application/json

###

GET {{QuantityMeasurementApp.HistoryService_HostAddress}}/api/history
Accept: application/json

###

GET {{QuantityMeasurementApp.HistoryService_HostAddress}}/api/history/user/test%40example.com
Accept: application/json

###

POST {{QuantityMeasurementApp.HistoryService_HostAddress}}/api/history
Content-Type: application/json

{
	"description": "Convert 1 Feet to Inches = 12",
	"isError": false,
	"userId": null
}

###
